name: Check non-i18n logging

on:
  push:
    branches:
      - 'test-1'

jobs:
  check-logging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run logging check
        shell: bash
        run: bash check_logging.sh
