name: WildFly JRE build

on:
  push:
    branches:
      - test
  pull_request:

jobs:
  wildfly-jre-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '17', '21-ea']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JRE ${{ matrix.java }} for building
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
          java-package: 'jre'

      - name: Set the JRE Home
        id: jre-home
        run: |
          echo "JRE_HOME=$JAVA_HOME" >> "$GITHUB_OUTPUT"

      - name: Setup JDK ${{ matrix.java }} for building
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build and verify WildFly with JRE ${{ matrix.java }}
        run: |
          mvn -B clean install -DskipTests -Denforcer.skip=true -Dcheckstyle.skip=true -Dts.basic
          cd testsuite
          echo "Running: mvn -B verify -Dcontainer.java.home=${{ steps.jre-home.outputs.JRE_HOME }} -Dts.basic -fae"
          mvn -B verify -Dcontainer.java.home=${{ steps.jre-home.outputs.JRE_HOME }} -Dts.basic -fae